#!/usr/bin/env bash
# Create the local secret files used by compose.yaml. Idempotent: existing values
# are never overwritten (delete a file explicitly to rotate it, then re-run).
#
# Layout: ./secrets is 0700 (protects the files on the host); files are 0644 so the
# non-root container users (uid 1000) can read the bind-mounted copies on Linux.
# The KatFile API key is never generated here: put it in secrets/katfile_api_key.
set -euo pipefail

cd "$(dirname "$0")/.."
umask 022
mkdir -p secrets
chmod 700 secrets

random_hex() { od -An -tx1 -N"$1" /dev/urandom | tr -d ' \n'; }

ensure_secret() {
  local file="secrets/$1" bytes="$2"
  if [[ -s "$file" ]]; then
    echo "keep    $file"
  else
    random_hex "$bytes" > "$file"
    echo "created $file"
  fi
  chmod 644 "$file"
}

ensure_secret worker_webhook_secret 32
ensure_secret worker_admin_token 32
ensure_secret sftpgo_admin_password 24
ensure_secret sftpgo_signing_passphrase 32
ensure_secret sftpgo_kms_master_key 32
ensure_secret caddy_admission_secret 32

# The worker's SFTPGo API key is created by scripts/sftpgo-bootstrap.sh; an empty
# placeholder lets compose start before the bootstrap has run.
if [[ ! -e secrets/sftpgo_worker_api_key ]]; then
  : > secrets/sftpgo_worker_api_key
  echo "created secrets/sftpgo_worker_api_key (empty until bootstrap)"
fi
chmod 644 secrets/sftpgo_worker_api_key

# SFTPGo reads secrets from env.d (not visible in `docker inspect`). Derived file:
# regenerated on every run from the component secrets above.
{
  echo "# Generated by scripts/init-secrets.sh; do not edit."
  echo "SFTPGO_DEFAULT_ADMIN_USERNAME=admin"
  echo "SFTPGO_DEFAULT_ADMIN_PASSWORD='$(cat secrets/sftpgo_admin_password)'"
  echo "SFTPGO_HTTP__HEADERS__0__VALUE='Bearer $(cat secrets/worker_webhook_secret)'"
  echo "SFTPGO_HTTPD__SIGNING_PASSPHRASE='$(cat secrets/sftpgo_signing_passphrase)'"
  echo "SFTPGO_KMS__SECRETS__MASTER_KEY='$(cat secrets/sftpgo_kms_master_key)'"
} > secrets/sftpgo.env
chmod 644 secrets/sftpgo.env
echo "wrote   secrets/sftpgo.env"

if [[ ! -s secrets/katfile_api_key ]]; then
  echo "WARNING: secrets/katfile_api_key is missing; the worker cannot reach KatFile." >&2
else
  chmod 644 secrets/katfile_api_key
fi
